In [1]:
from molecule import Molecule
from molpro import Molpro
from pes import PES
from avg_pes import Avg_PES
import numpy as np
# lee woodcock
#  replica exchange rxn path simulation?

In [2]:
filepath='examples/tests/fluoroethene.xyz'
nocc=11
nactive=2
lot=Molpro.from_options(states=[(1,0),(1,1)],charge=0,nocc=nocc,nactive=nactive,basis='6-31G',do_coupling=False,nproc=4,fnm=filepath)
pes1 = PES.from_options(lot=lot,ad_idx=0,multiplicity=1)
pes2 = PES.from_options(lot=lot,ad_idx=1,multiplicity=1)
pes = Avg_PES(pes1,pes2,lot=lot)
M = Molecule.from_options(fnm=filepath,PES=pes,coordinate_type="DLC")


 initializing LOT from file
 reading cartesian coordinates from file
 building coordinate object
 making primitives from options!
 making primitive Hessian
printing diagonals
[0.35, 0.35, 0.35, 0.35, 0.35, 0.16, 0.16, 0.16, 0.16, 0.045, 0.045, 0.023, 0.023, 0.023, 0.023]
forming Hessian in basis


In [7]:
print(M)

 molecule object
Option:
  Key: fnm
  Value: examples/tests/fluoroethene.xyz
  Required: False
  Allowed Types: [<class 'str'>]
  Allowed Values: None
  Doc: File name to create the Molecule object from. Only used if geom is none.

Option:
  Key: ftype
  Value: xyz
  Required: False
  Allowed Types: [<class 'str'>]
  Allowed Values: None
  Doc: filetype (optional) will attempt to read filetype if not given

Option:
  Key: coordinate_type
  Value: DLC
  Required: False
  Allowed Types: None
  Allowed Values: ['Cartesian', 'DLC', 'HDLC', 'TRIC']
  Doc: The type of coordinate system to build

Option:
  Key: coord_obj
  Value: Internal coordinate system (atoms numbered from 1):
Distance 1-2
Distance 1-3
Distance 1-4
Distance 2-5
Distance 2-6
Angle 2-1-4
Angle 3-1-4
Angle 1-2-6
Angle 5-2-6
Out-of-Plane 1-2-3-4
Out-of-Plane 2-1-5-6
Dihedral 3-1-2-5
Dihedral 3-1-2-6
Dihedral 4-1-2-5
Dihedral 4-1-2-6
<class 'slots.Distance'> : 5
<class 'slots.Angle'> : 4
<class 'slots.OutOfPlane'> : 2
<class '

In [18]:
print("printing gradient")
print(M.gradient)

printing gradient
turning gradient off for demonstration purpose
#gradx = self.PES.get_gradient(self.xyz) 
#return self.coord_obj.calcGrad(self.xyz,gradx)  #CartesianCoordinate just returns gradx
0.0


In [4]:
M.energy

turning energy off for demonstration purpose
self.PES.get_energy(self.xyz)


0.0

In [9]:
print("primitive internal coordinates")
print(M.primitive_internal_coordinates)

primitive internal coordinates
[Distance 1-2, Distance 1-3, Distance 1-4, Distance 2-5, Distance 2-6, Angle 2-1-4, Angle 3-1-4, Angle 1-2-6, Angle 5-2-6, Out-of-Plane 1-2-3-4, Out-of-Plane 2-1-5-6, Dihedral 3-1-2-5, Dihedral 3-1-2-6, Dihedral 4-1-2-5, Dihedral 4-1-2-6]


In [10]:
print("primitive number of internal coordinates")
print(M.num_primitives)

primitive number of internal coordinates
15


In [13]:
print("getting the value of a primitive 0")
print(M.primitive_internal_coordinates[0].value(M.xyz))

getting the value of a primitive 0
1.3308189789788099


In [16]:
print("printing delocalized coordinates basis")
print(M.coord_basis)

printing delocalized coordinates basis
[[ 0.2806  0.7797  0.0219  0.0115  0.2771  0.1212 -0.0572 -0.      0.4618
  -0.0689 -0.     -0.    ]
 [ 0.1298  0.169  -0.2278 -0.6333 -0.458   0.4353 -0.0464 -0.     -0.2171
  -0.2307  0.      0.    ]
 [-0.0926  0.2978  0.4327 -0.3329 -0.2935 -0.5792  0.4061  0.     -0.0625
   0.1192  0.      0.    ]
 [ 0.1007  0.1706  0.3     0.553  -0.5149  0.4271  0.1702 -0.     -0.1185
   0.2728  0.      0.    ]
 [-0.0186  0.2794 -0.452   0.3067 -0.4016 -0.4805 -0.4503 -0.     -0.1473
  -0.0813 -0.      0.    ]
 [-0.5606  0.2831  0.3034  0.1328  0.2021  0.1383 -0.1191 -0.     -0.4033
  -0.509  -0.     -0.    ]
 [-0.4764 -0.0735  0.2677 -0.1944 -0.2408  0.1007 -0.528  -0.      0.4964
   0.2546 -0.     -0.    ]
 [-0.4709  0.2752 -0.4505 -0.0787  0.194   0.1311  0.2309  0.     -0.1891
   0.5912  0.     -0.    ]
 [-0.3498 -0.0805 -0.3154  0.163  -0.2539  0.0253  0.5015  0.      0.505
  -0.4164 -0.     -0.    ]
 [ 0.     -0.      0.     -0.     -0.     -0.     -0.

In [17]:
print("printing coordinates in basis")
print(M.coordinates.T)

printing coordinates in basis
[[-3.3507  2.9312 -0.3838 -0.2259 -1.7651  0.8945  0.1756 -0.7082  0.8046
  -0.2303 -3.8206  0.3328]]


In [19]:
dq = np.zeros((M.num_coordinates,1))
dq[0]=0.1
print("taking step and printing new xyz,geom and coordinates")
M.update_xyz(dq)
print(M.coordinates.T)
print(M.xyz)
print(M.geometry)

taking step and printing new xyz,geom and coordinates
Iter: 1 Err-dQ = 7.95491e-03 RMSD: 4.33434e-02 Damp: 1.00000e+00
Iter: 2 Err-dQ (Best) = 7.11647e-06 (7.95491e-03) RMSD: 1.74577e-03 Damp: 1.00000e+00 (Good)
Iter: 3 Err-dQ (Best) = 1.99785e-11 (7.11647e-06) RMSD: 1.90451e-06 Damp: 1.00000e+00 (Good)
Cartesian coordinates obtained after 3 microiterations (rmsd = 1.905e-06 |dQ| = 1.998e-11)
[[-3.2507  2.9312 -0.3838 -0.2259 -1.7651  0.8945  0.1756 -0.7082  0.8046
  -0.2303 -3.8206  0.3328]]
[[-4.5196  2.1864 -0.0125]
 [-3.1607  2.1785 -0.0094]
 [-5.3255  2.927   0.8144]
 [-5.0128  1.5534 -0.7297]
 [-2.5303  2.7705  0.6628]
 [-2.6585  1.5386 -0.7256]]
[('C', -4.519592215522, 2.186404141203442, -0.012487458677285491), ('C', -3.160741509350698, 2.178468608567302, -0.009423871902693445), ('F', -5.325509747676559, 2.926982944734106, 0.814363599179425), ('H', -5.0128146188298786, 1.5533528811519122, -0.7297239456612628), ('H', -2.530329626444841, 2.7705154864525054, 0.6628489584930248), ('

In [21]:
# update coordinate basis
print("update coordinate basis")
print(M.update_coordinate_basis())  #also used with constraints


update coordinate basis
[[ 0.26    0.7873 -0.0223  0.0038  0.2846  0.086  -0.055  -0.      0.4624
  -0.083  -0.     -0.    ]
 [ 0.134   0.2025  0.2056 -0.6252 -0.4711  0.4216 -0.0214 -0.     -0.2368
  -0.2274 -0.      0.    ]
 [-0.1093  0.2734 -0.4509 -0.2922 -0.3045 -0.593   0.4017  0.     -0.0552
   0.1257  0.      0.    ]
 [ 0.109   0.1942 -0.2827  0.5808 -0.4847  0.4229  0.1535 -0.     -0.1214
   0.2848  0.      0.    ]
 [-0.0339  0.2628  0.466   0.3002 -0.3922 -0.4846 -0.4538 -0.     -0.1457
  -0.0815 -0.      0.    ]
 [-0.5617  0.2703 -0.3049  0.1373  0.2143  0.1315 -0.1259 -0.     -0.4203
  -0.4938 -0.     -0.    ]
 [-0.474  -0.0765 -0.2634 -0.1928 -0.2553  0.127  -0.5248 -0.      0.4995
   0.2381 -0.     -0.    ]
 [-0.4761  0.268   0.4459 -0.0951  0.1987  0.1195  0.2363  0.     -0.1762
   0.5942  0.      0.    ]
 [-0.3502 -0.0828  0.3092  0.1768 -0.2549  0.0434  0.5084  0.      0.4837
  -0.4293 -0.     -0.    ]
 [ 0.     -0.     -0.     -0.     -0.     -0.     -0.      0.029   

In [22]:
print("coords in new basis")
print(M.coordinates.T)


coords in new basis
[[-3.3073  2.9176  0.3508 -0.1511 -1.7389  0.857   0.2036 -0.5931  0.7394
  -0.2478 -3.7931  0.3119]]


In [23]:
print("update Hessian in  basis")
print(M.form_Hessian_in_basis())


update Hessian in  basis
[[ 0.181   0.0407  0.0046  0.0004  0.0009  0.0392 -0.0055 -0.      0.0164
  -0.0061  0.      0.    ]
 [ 0.0407  0.3201 -0.006  -0.0022 -0.0288 -0.0103 -0.0052 -0.      0.0454
  -0.0082 -0.      0.    ]
 [ 0.0046 -0.006   0.2632 -0.004  -0.0022  0.0013 -0.0834 -0.     -0.0129
  -0.0418 -0.     -0.    ]
 [ 0.0004 -0.0022 -0.004   0.3317 -0.0028  0.0019 -0.0287 -0.      0.0098
   0.0468 -0.     -0.    ]
 [ 0.0009 -0.0288 -0.0022 -0.0028  0.309  -0.0016 -0.0046 -0.      0.0714
  -0.0116 -0.     -0.    ]
 [ 0.0392 -0.0103  0.0013  0.0019 -0.0016  0.3406  0.0062 -0.     -0.0015
  -0.0034 -0.     -0.    ]
 [-0.0055 -0.0052 -0.0834 -0.0287 -0.0046  0.0062  0.2349  0.      0.0009
   0.0267  0.      0.    ]
 [-0.     -0.     -0.     -0.     -0.     -0.      0.      0.0232 -0.
  -0.      0.0008 -0.0005]
 [ 0.0164  0.0454 -0.0129  0.0098  0.0714 -0.0015  0.0009 -0.      0.2187
  -0.0027 -0.     -0.    ]
 [-0.0061 -0.0082 -0.0418  0.0468 -0.0116 -0.0034  0.0267 -0.     -0.0

In [9]:

# copying molecule automatically copies all Data
print("copy molecule")
newMolecule = Molecule.copy_from_options(M)
print("\n")
print("###############################")
print("Note that the copy from options is recommended since it properly creates new coord_obj and PES object")

copy molecule
 creating copy, new node id = 1
 old node id =  0
  cp scratch/mp_0000_000 scratch/mp_0000_001
 initializing LOT from file
 making primitives from options!
 getting cartesian coordinates from geom
 getting coord_object from options


###############################
Note that the copy from options is recommended since it properly creates new coord_obj and PES object


In [10]:
print(newMolecule)

 molecule object
Option:
  Key: fnm
  Value: examples/tests/fluoroethene.xyz
  Required: False
  Allowed Types: [<class 'str'>]
  Allowed Values: None
  Doc: File name to create the Molecule object from. Only used if geom is none.

Option:
  Key: ftype
  Value: xyz
  Required: False
  Allowed Types: [<class 'str'>]
  Allowed Values: None
  Doc: filetype (optional) will attempt to read filetype if not given

Option:
  Key: coordinate_type
  Value: DLC
  Required: False
  Allowed Types: None
  Allowed Values: ['Cartesian', 'DLC', 'HDLC', 'TRIC']
  Doc: The type of coordinate system to build

Option:
  Key: coord_obj
  Value: Internal coordinate system (atoms numbered from 1):
Distance 1-2
Distance 1-3
Distance 1-4
Distance 2-5
Distance 2-6
Angle 2-1-4
Angle 3-1-4
Angle 1-2-6
Angle 5-2-6
Out-of-Plane 1-2-3-4
Out-of-Plane 2-1-5-6
Dihedral 3-1-2-5
Dihedral 3-1-2-6
Dihedral 4-1-2-5
Dihedral 4-1-2-6
<class 'slots.Distance'> : 5
<class 'slots.Angle'> : 4
<class 'slots.OutOfPlane'> : 2
<class '

In [28]:
print("copy molecule with new geom")
newxyz2 = np.ones(M.xyz.shape)
newxyz2 += M.xyz
newMolecule2 = Molecule.copy_from_options(M,xyz=newxyz2)
print(newMolecule2.xyz)


copy molecule with new geom
 creating copy, new node id = 1
 old node id =  0
  cp scratch/mp_0000_000 scratch/mp_0000_001
 initializing LOT from file
 making primitives from options!
 getting cartesian coordinates from geom
 getting coord_object from options
[[-3.5196  3.1864  0.9875]
 [-2.1607  3.1785  0.9906]
 [-4.3255  3.927   1.8144]
 [-4.0128  2.5534  0.2703]
 [-1.5303  3.7705  1.6628]
 [-1.6585  2.5386  0.2744]]


In [36]:
from eigenvector_follow import eigenvector_follow
ef = eigenvector_follow.from_options() #Linesearch=NoLineSearch)

In [39]:
ef.optimize(
    molecule=M,
    refE=M.energy,
    opt_steps=5
)

turning energy off for demonstration purpose
self.PES.get_energy(self.xyz)
turning energy off for demonstration purpose
self.PES.get_energy(self.xyz)
initial E 0.0000
turning energy off for demonstration purpose
self.PES.get_energy(self.xyz)
turning energy off for demonstration purpose
self.PES.get_energy(self.xyz)
turning gradient off for demonstration purpose
#gradx = self.PES.get_gradient(self.xyz) 
#return self.coord_obj.calcGrad(self.xyz,gradx)  #CartesianCoordinate just returns gradx


AttributeError: 'float' object has no attribute 'copy'